services:
    vinny.sidebar.listener:
        class: vinny\sidebar\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '@auth'
            - '@dispatcher'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '@cache.driver'
        tags:
            - { name: event.listener }
